version: "3"

services:
  federation-forms-db:
    image: mysql:8.0.27
    container_name: federation-forms-db
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "docker"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      TZ: "Asia/Tokyo"
    ports:
      - "3311:3306"
